services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      DB_URL: $DB_URL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.8
    container_name: redis
    restart: always
    command: redis-server
    depends_on:
      - wallets

  wallets:
    container_name: wallets
    build: ./wallets
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data: