services:

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.8
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - 6379:6379

  wallets:
    container_name: wallets
    build: ./wallets
    env_file:
      - .env
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: